<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-TGN9GU3D" failures="0" tests="2" name="TestCases.DemoInvocationTimeOutTest" time="20.903" errors="1" timestamp="2023-01-09T00:35:39 IST" skipped="1">
  <testcase classname="TestCases.DemoInvocationTimeOutTest" name="verifyCurrentUrlTest" time="20.903">
    <error message="Method TestCases.DemoInvocationTimeOutTest.verifyCurrentUrlTest() didn&#039;t finish within the time-out 200" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestCases.DemoInvocationTimeOutTest.verifyCurrentUrlTest() didn't finish within the time-out 200
]]>
    </error>
  </testcase> <!-- verifyCurrentUrlTest -->
  <testcase classname="TestCases.DemoInvocationTimeOutTest" name="verifyTitleTest">
    <skipped/>
  </testcase> <!-- verifyTitleTest -->
</testsuite> <!-- TestCases.DemoInvocationTimeOutTest -->
